### ISSUE TITLE
larger file format issue?

### ISSUE THREAD

**Issue by gmarquart** [ries-lab/Accent#20]
`accent-fiji-1.0.jar` doesn't appear to work with larger xy file formats (e.g., 2048x2048 or 1024x1024) -- while if I scale/crop to 512x512, it runs without error.  I'm guessing that somewhere the 4 vs. 3 digits breaks the code?

example error:

`[ERROR] Error reading IFD type at: 34360787204`
`Exception in thread "Thread-6" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1`
`	at java.util.ArrayList.rangeCheck(ArrayList.java:659)`
`	at java.util.ArrayList.get(ArrayList.java:435)`
`	at io.scif.formats.MinimalTIFFFormat$Reader.openPlane(MinimalTIFFFormat.java:562)`
`	at io.scif.formats.MinimalTIFFFormat$Reader.openPlane(MinimalTIFFFormat.java:530)`
`	at io.scif.AbstractReader.openPlane(AbstractReader.java:169)`
`	at io.scif.filters.ChannelFiller.openPlane(ChannelFiller.java:164)`
`	at io.scif.filters.ChannelFiller.openPlane(ChannelFiller.java:147)`
`	at io.scif.filters.PlaneSeparator.openPlane(PlaneSeparator.java:289)`
`	at io.scif.filters.AbstractReaderFilter.openPlane(AbstractReaderFilter.java:251)`
`	at io.scif.img.ImgOpener.read(ImgOpener.java:755)`
`	at io.scif.img.ImgOpener.read(ImgOpener.java:736)`
`	at io.scif.img.ImgOpener.read(ImgOpener.java:717)`
`	at io.scif.img.ImgOpener.readPlanes(ImgOpener.java:704)`
`	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:432)`
`	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:358)`
`	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:329)`
`	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:244)`
`	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:152)`
`	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:133)`
`	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:138)`
`	at de.embl.rieslab.accent.fiji.loader.SingleImgLoader.loadNext(SingleImgLoader.java:86)`
`	at de.embl.rieslab.accent.fiji.loader.SingleImgLoader.getNext(SingleImgLoader.java:59)`
`	at de.embl.rieslab.accent.fiji.loader.SingleImgLoader.getNext(SingleImgLoader.java:22)`
`	at de.embl.rieslab.accent.fiji.processor.ImgProcessor.computeAvgAndVar(ImgProcessor.java:46)`
`	at de.embl.rieslab.accent.common.processor.CalibrationProcessor.runProcess(CalibrationProcessor.java:106)`
`	at de.embl.rieslab.accent.common.processor.CalibrationProcessor.run(CalibrationProcessor.java:69)`

**Comment by gmarquart** [comment]
looks like it's an issue with the default tif format saved by Fiji.  appears to run on tifs saved with save as > OME-TIFF.

**Comment by jdeschamps** [comment]
Thanks for letting us know!

I don't really have the bandwidth to look into this , but it looks like a problem in SCIFIO rather than Accent. I'll keep an eye out and updated the README with your solution. 

I'll leave the issue open in case someone else runs into this or until I get around to find a fix.
